# SITE CONFIGURATION
title: FPGA based power estimator # your site title
author: Jerry Jin, Yujie Lu # You :P
description: > # Meta description of Homepage
  This is the final project of ECE5760. We built a power estimator using an FPGA and a current sensor board. 
  Find out more by reading!

baseurl: "ece5760_final_webpage" # the subpath of your site, e.g. /blog
url: https://404codercn.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: janczizikow/sleek
# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://github.com/404coderCN


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  An ECE5760 final project

hero_img: assets/img/posts/main_background.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jerrykim2001216@gmail.com # email for form submission

github_username:  404coderCN # replace with your_github_username or comment to remove link from footer


# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
